# CLIENT
steps:
- name: "gcr.io/cloud-builders/yarn"
  args: ["install"]
  dir: 'packages/client'
- name: "gcr.io/cloud-builders/gcloud"
  args:
  -  kms 
  - decrypt
  -  --key=cloudbuild-env
  -  --keyring=brimble-auth
  -  --location=global  
  -  --plaintext-file=.env                     
  -  --ciphertext-file=.env.enc
  dir: 'packages/client'
- name: "gcr.io/cloud-builders/yarn"
  args: ["build"]
  dir: 'packages/client'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  dir: 'packages/client'

# API
- name: "gcr.io/cloud-builders/yarn"
  args: ["install"]
  dir: 'packages/api'
- name: "gcr.io/cloud-builders/gcloud"
  args:
  -  kms 
  - decrypt
  -  --key=cloudbuild-env
  -  --keyring=brimble-auth
  -  --location=global  
  -  --plaintext-file=.env.prod                     
  -  --ciphertext-file=.env.prod.enc
  dir: 'packages/api'  
- name: "gcr.io/cloud-builders/yarn"
  args: ["build"]
  dir: 'packages/api'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "api.yaml"]
  dir: 'packages/api'
options:
 logging: CLOUD_LOGGING_ONLY
timeout: "1600s"